### PR TITLE
Wqp 1167 allow huc 12

### PR DESCRIPTION
**Pull request by ayan-usgs**

### CODE REVIEW

**Comment by jkreft-usgs** [comment]
I'm really sorry that i didn't make this explicit in the ticket.  A HUC10 should also be allowed, to follow the existing pattern (2,4,6,8 etc)

**Comment by ayan-usgs** [comment]
> I'm really sorry that i didn't make this explicit in the ticket. A HUC10 should also be allowed, to follow the existing pattern (2,4,6,8 etc)

Okay.

**Comment by ayan-usgs** [comment]
Made some modifications to support HUC10.

**Comment by ayan-usgs** [comment]
Turns out I forgot to push my HUC 10 changes. :gun:

**Pull request merged**
